version: "3.1"


services:
  jupyterhub:
    image: jupyterhub/jupyterhub
    volumes:
      - .:/srv/jupyterhub
    ports:
      - 8000:8000

  kbatch-server:
    # build: ..
    image: tomaugspurger/kbatch-server
    volumes:
      - ..:/code
      - .:/config
    ports:
      - 8050:8050
    environment:
      JUPYTERHUB_API_TOKEN: super-secret
      JUPYTERHUB_API_URL: http://jupyterhub:8000/hub/api
      JUPYTERHUB_HOST: http://127.0.0.1:8000
      DJANGO_SETTINGS_MODULE: kbatch_server.settings.local