[tool.black]
line-length = 88
target-version = ['py39']

[tool.pytest.ini_options]
# GitHub Actions make it hard for pytest to conlcude it should use colors, due
# to this we explicitly make it do so. This is related to:
# https://github.com/actions/runner/issues/241
addopts = '--color=yes'

