[tool.black]
line-length = 88
target-version = ['py39']
extend-exclude = '''
django_kbatch_server/migrations/.*.py
'''

[tool.pytest.ini_options]
# GitHub Actions make it hard for pytest to conlcude it should use colors, due
# to this we explicitly make it do so. This is related to:
# https://github.com/actions/runner/issues/241
addopts = '--color=yes'

[tool.mypy]
warn_unused_configs = true
exclude = "kbatch-server/(docker|setup.py|manage.py|kbatch_server/settings/base.py)"
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "kbatch_server.settings.local"


[[tool.mypy.overrides]]
module = [
    "escapism",
    "sqlalchemy",
    "jupyterhub",
    "jupyterhub.services",
    "jupyterhub.services.auth",
    "kubernetes",
    "kubernetes.client",
    "kubernetes.client.models",
    "django.core.wsgi",
    "rest_framework",
    "rest_framework.authentication",
    "rest_framework.exceptions",
    "rest_framework.parsers",
    "rest_framework.test",
]
ignore_missing_imports = true