version: "3.1"

services:
  hub:
    image: jupyterhub/jupyterhub
    volumes:
      - .:/srv/jupyterhub
    ports:
      - 8000:8000

  kbatch-server:
    build:
      context: ../..
      dockerfile: ./docker/local/Dockerfile
    image: kbatch_local_image
    command: /start
    volumes:
      - ../..:/code
    ports:
      - 8050:8050
    # env_file:
    #   - ../../.envs/.local/.django
    environment:
      JUPYTERHUB_API_TOKEN: super-secret
      JUPYTERHUB_API_URL: http://jupyterhub:8000/hub/api
      JUPYTERHUB_HOST: http://127.0.0.1:8000
      JUPTYERHUB_SERVICE_PREFIX: services/kbatch/
      DJANGO_SETTINGS_MODULE: kbatch_server.settings.local
