# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-server
  HELM_NAME: ${{ github.repository_owner }}/charts/${{ github.event.repository.name }}
  HELM_EXPERIMENTAL_OCI: 1  # enables publishing Helm images to GHCR

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set the tag
        id: tag
        run: |
          GITHUB_TAG=${GITHUB_REF/refs\/tags\//}
          echo "::set-output name=tag::${GITHUB_TAG}"

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: kbatch-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Install helm
        uses: Azure/setup-helm@v1

      - name: Login helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.REGISTRY }}/${{ env.HELM_NAME }} -u ${{ github.repository_owner }} --password-stdin
      - name: Save chart locally
        run: |
          helm chart save ./kbatch-server/helm/kbatch-server ${{ env.REGISTRY }}/${{ env.HELM_NAME }}:${{ steps.tag.outputs.tag }}
      - name: Publish chart
        run: |
          helm chart push ${{ env.REGISTRY }}/${{ env.HELM_NAME }}:${{ steps.tag.outputs.tag }}
