name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches:
      - main

env:
  commit_msg: ${{ github.event.head_commit.message }}

jobs:
  main-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: nolar/setup-k3d-k3s@v1
      - name: Check k3d
        run: |
          k3d --version
          kubectl get nodes

      - name: Install requirements
        run: |
          source continuous_integration/install.sh

      - name: List Packages
        run: |
          pip freeze

      - name: Run Tests
        run: |
          cd ksubmit-server
          KBATCH_SETTINGS_PATH=.env.test pytest -v